# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jack Schaedler
tagline:          'My Personal Blog'
url:              http://jackschaedler.github.io/
paginate:         1
author:
  name:           Jack Schaedler
  url:            https://twitter.com/jackschaedler
  email:          jwschaedler@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'